# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ChaosNetz
email: netz@koeln.ccc.de
description: > # this means to ignore newlines until "baseurl:"
  ChaosNetz ist ein Projekt des Chaos Computer Club Cologne (C4) e.V.
  zur Bildung und Völkerverständigung
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chaosnetz.org" # the base hostname & protocol for your site
twitter_username: ccc_koeln
github_username:  cccc

# Build settings
markdown: kramdown
